name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Yarn
        run: yarn install --frozen-lockfile
        working-directory: ./apps/server
      - name: tsc
        run: yarn tsc
        working-directory: ./apps/server
      - name: Lint
        run: yarn lint
        working-directory: ./apps/server
      - name: Test
        run: yarn test
        working-directory: ./apps/server
